### ISSUE TITLE
Request for Dependency Management Enhancement in ktor-server-task-scheduling

### ISSUE THREAD

**Issue by tb-kpabla** [Flaxoos/extra-ktor-plugins#30]
Hi Flaxoos,

I've encountered a small issue and would like to suggest a possible enhancement. Currently, the library bundles all its dependencies into the jar file. This approach, while self-contained, leads to a significant issue with Gradle in my project as it flags every single class as duplicated due to the bundled dependencies and refuses to compile.

Would it be possible to consider adding another build configuration that lets Gradle handle the transitive dependencies at build time instead? This change would help avoid the duplication issue and let us use this library in our project.

Thank you for considering this suggestion. 
Looking forward to your thoughts.

**Comment by Szczypiorek44** [comment]
Hi,
I have exactly the same issue :)

**Comment by Flaxoos** [comment]
Hi Guys, thanks for your input, and sorry for the late response

@tb-kpabla @Szczypiorek44 could you please share more details, like which jars are conflicting?

I am using the gradle shadow plugin, perhaps i missed some config

In any case, did you try using the various [solutions](https://docs.gradle.org/current/userguide/dependency_version_alignment.html) gradle offers?

**Comment by Flaxoos** [comment]
@Szczypiorek44 Thanks for the info, i'll make a ticket for it, i think it's probably solvable with a simple Shade plugin config. 

BTW, you're welcome to also contribute to the repo by creating a PR to fix this, as i'm currently the only maintainer, so help would be appreciated :)

**Comment by Flaxoos** [comment]
@Szczypiorek44 I'm on it. Could you maybe please provide a minimal reproduction of the issue so i can validate it?

**Comment by Szczypiorek44** [comment]
Sure. All I did was I've created new project in Android Studio, and in my `build.gradle` I've added the ktor and your plugin:
```
    implementation(libs.ktor.server.core) //I'm using toml
    implementation(libs.ktor.server.callLogging)
    implementation(libs.ktor.contentNegotiator)
    implementation(libs.ktor.serialization.json)
    implementation(libs.slf4j.android)

    implementation("io.github.flaxoos:ktor-server-task-scheduling-jdbc:1.2.8")
```

That's it, it should be enough to recreate the issue.
In case you need it here's my MainActivity:
```
class MainActivity : ComponentActivity() {
    private val environment by lazy { createEnvironment() }
    private val server by lazy { embeddedServer(Netty, environment) }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
        ...
        }

        server.start()
    }

    private fun createEnvironment(): ApplicationEngineEnvironment =
        applicationEngineEnvironment {
            log = LoggerFactory.getLogger("ktor.application")
            connector {
                port = 8000
            }
            module {
                module()
            }
        }
}
```

**Comment by Szczypiorek44** [comment]
If you'll have a problem with recreating the issue let me know, then I'll give you access to my repo

**Comment by Flaxoos** [comment]
@Szczypiorek44 Ok i'm removing the fat jar, this should solve the issue. there is a dependencyt on another lib of mine though, that is not yet hosted on maven central, and only on GH packages, which doesn't offer open read access, so i will need to host it on central which might take a few days. in the meantime i can add it to this repository

**Comment by Flaxoos** [comment]
@Szczypiorek44 i just released a new version, 1.2.10, can you please try it and see if your issue is solved?

**Comment by Szczypiorek44** [comment]
Hi @Flaxoos , sorry for the late reply.
So I've just updated dependency to:
`    implementation("io.github.flaxoos:ktor-server-task-scheduling-jdbc:1.2.10")`

Unfortunately, issue still persists:
```
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class _COROUTINE.ArtificialStackFrames found in the following modules: kotlinx-coroutines-core-jvm-1.7.3 (org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.7.3), ktor-server-task-scheduling-core-jvm-1.2.10 (io.github.flaxoos:ktor-server-task-scheduling-core-jvm:1.2.10) and ktor-server-task-scheduling-jdbc-jvm-1.2.10 (io.github.flaxoos:ktor-server-task-scheduling-jdbc-jvm:1.2.10)
     Duplicate class _COROUTINE.CoroutineDebuggingKt found in the following modules: kotlinx-coroutines-core-jvm-1.7.3 (org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.7.3), ktor-server-task-scheduling-core-jvm-1.2.10 (io.github.flaxoos:ktor-server-task-scheduling-core-jvm:1.2.10) and ktor-server-task-scheduling-jdbc-jvm-1.2.10 (io.github.flaxoos:ktor-server-task-scheduling-jdbc-jvm:1.2.10)
     Duplicate class _COROUTINE._BOUNDARY found in the following modules: kotlinx-coroutines-core-jvm-1.7.3 (org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.7.3), ktor-server-task-scheduling-core-jvm-1.2.10 (io.github.flaxoos:ktor-server-task-scheduling-core-jvm:1.2.10) and ktor-server-task-scheduling-jdbc-jvm-1.2.10 (io.github.flaxoos:ktor-server-task-scheduling-jdbc-jvm:1.2.10)
     Duplicate class _COROUTINE._CREATION found in the following modules: kotlinx-coroutines-core-jvm-1.7.3 (org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.7.3), ktor-server-task-scheduling-core-jvm-1.2.10 (io.github.flaxoos:ktor-server-task-scheduling-core-jvm:1.2.10) and ktor-server-task-scheduling-jdbc-jvm-1.2.10 (io.github.flaxoos:ktor-server-task-scheduling-jdbc-jvm:1.2.10)
     Duplicate class arrow.atomic.AtomicActual found in the following modules: arrow-atomic-jvm-1.2.0 (io.arrow-kt:arrow-atomic-jvm:1.2.0), ktor-server-task-scheduling-core-jvm-1.2.10 (io.github.flaxoos:ktor-server-task-scheduling-core-jvm:1.2.10) and ktor-server-task-scheduling-jdbc-jvm-1.2.10 (io.github.flaxoos:ktor-server-task-scheduling-jdbc-jvm:1.2.10)
...
     Duplicate class io.github.flaxoos.ktor.server.plugins.taskscheduling.TaskConfiguration found in modules ktor-server-task-scheduling-core-jvm-1.2.10 (io.github.flaxoos:ktor-server-task-scheduling-core-jvm:1.2.10) and ktor-server-task-scheduling-jdbc-jvm-1.2.10 (io.github.flaxoos:ktor-server-task-scheduling-jdbc-jvm:1.2.10)
...
     Duplicate class io.ktor.client.HttpClient found in the following modules: ktor-client-core-jvm-2.3.2 (io.ktor:ktor-client-core-jvm:2.3.2), ktor-server-task-scheduling-core-jvm-1.2.10 (io.github.flaxoos:ktor-server-task-scheduling-core-jvm:1.2.10) and ktor-server-task-scheduling-jdbc-jvm-1.2.10 (io.github.flaxoos:ktor-server-task-scheduling-jdbc-jvm:1.2.10)
   
```

**Comment by Flaxoos** [comment]
@Szczypiorek44 Fix is in https://github.com/Flaxoos/extra-ktor-plugins/pull/61

**Comment by Szczypiorek44** [comment]
Hi @Flaxoos 
Great news! I'll try to test it soon. Thanks
